name = "FloquetEngineeringToricCode"
uuid = "1ca9f05b-88e6-4bad-b139-a318c63050a4"
authors = ["Wanda0929 <hwang924@connect.hkust-gz.edu.cn> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PauliPropagation = "293282d5-3c99-4fb6-92d0-fd3280a19750"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"

[compat]
LinearAlgebra = "1.11.0"
PauliPropagation = "0.1.1"
Yao = "0.9.0"
YaoBlocks = "0.13.14"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
